allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - '@opennextjs/aws@4.1.0'
  - '@opennextjs/cloudflare@1.20.2'
